# Generated by Django 4.2.4 on 2023-09-18 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.ImageField(upload_to='photos/')),
                ('product_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('price', models.CharField()),
                ('post_date', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
